### ISSUE TITLE
Crash w/ ValleyCraft & Capybara 1.07

### ISSUE THREAD

**Issue by nephatrine** [ZestyBlaze/Capybara-UAM#18]
using:

capybara-1.18.2-1.0.7
valley-craft-2.3.1-1.18.2

I got this crash:

```
java.lang.ClassCastException: class io.github.linkle.valleycraft.entities.SardineEntity cannot be cast to class net.minecraft.class_1321 (io.github.linkle.valleycraft.entities.SardineEntity and net.minecraft.class_1321 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @b97c004)
	at net.zestyblaze.capybara.entity.ai.CapybaraAnimalAttractionGoal.start(CapybaraAnimalAttractionGoal.java:28)
	at net.minecraft.entity.ai.goal.PrioritizedGoal.start(PrioritizedGoal:41)
	at net.minecraft.entity.ai.goal.GoalSelector.tick(GoalSelector:106)
	at net.minecraft.entity.mob.MobEntity.tickNewAi(MobEntity:742)
	at net.minecraft.entity.LivingEntity.tickMovement(LivingEntity:2609)
	at net.minecraft.entity.mob.MobEntity.tickMovement(MobEntity:546)
	at net.minecraft.entity.passive.PassiveEntity.tickMovement(PassiveEntity:127)
	at net.minecraft.entity.passive.AnimalEntity.tickMovement(AnimalEntity:58)
	at net.minecraft.entity.LivingEntity.tick(LivingEntity:2354)
	at net.minecraft.entity.mob.MobEntity.tick(MobEntity:346)
	at net.zestyblaze.capybara.entity.CapybaraEntity.tick(CapybaraEntity.java:231)
	at net.minecraft.server.world.ServerWorld.tickEntity(ServerWorld:702)
	at net.minecraft.world.World.tickEntity(World:485)
	at net.minecraft.server.world.ServerWorld.method_31420(ServerWorld:363)
	at net.minecraft.world.EntityList.forEach(EntityList:54)
	at net.minecraft.server.world.ServerWorld.tick(ServerWorld:331)
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:907)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer:851)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer:97)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:273)
	at java.lang.Thread.run(Thread.java:833)
```

I had been using capybara-1.18.2-1.0.6 and did not experience this error until I updated.

**Comment by Seceroth** [comment]
Same problem here, but with an interaction from the betteranimalsplus mod.

[crash-2022-09-26_15.44.50-server.txt](https://github.com/ZestyBlaze/Capybara-Fabricated/files/9653127/crash-2022-09-26_15.44.50-server.txt)

After this crash, the server still runs but stalls resulting in this crash (single tick took too long):
[crash-2022-09-26_15.49.51-server.txt](https://github.com/ZestyBlaze/Capybara-Fabricated/files/9653132/crash-2022-09-26_15.49.51-server.txt)

**Comment by ZestyBlaze** [comment]
Should be fixed in latest update
